version: '3.7'
# ====================================== AIRFLOW ENVIRONMENT VARIABLES =======================================
x-environment: &airflow_environment
  - AIRFLOW__CORE__EXECUTOR=${AIRFLOW__CORE__EXECUTOR}
  - AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS=${AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS}
  - AIRFLOW__CORE__LOAD_EXAMPLES=${AIRFLOW__CORE__LOAD_EXAMPLES}
  - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
  - AIRFLOW__CORE__STORE_DAG_CODE=${AIRFLOW__CORE__STORE_DAG_CODE}
  - AIRFLOW__CORE__STORE_SERIALIZED_DAGS=${AIRFLOW__CORE__STORE_SERIALIZED_DAGS}
  - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=${AIRFLOW__WEBSERVER__EXPOSE_CONFIG}
  - AIRFLOW__WEBSERVER__RBAC=${AIRFLOW__WEBSERVER__RBAC}
x-airflow-image: &airflow_image apache/airflow:2.0.0-python3.8
# ====================================== /AIRFLOW ENVIRONMENT VARIABLES ======================================
services:
  postgres:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432"
  init:
    image: *airflow_image
    depends_on:
      - postgres
    environment: *airflow_environment
    entrypoint: /bin/bash
    command: -c 'airflow db upgrade && sleep 5 && airflow users create --username ${AIRFLOW_INIT_USERNAME} --password ${AIRFLOW_INIT_PASSWORD} --firstname ${AIRFLOW_INIT_FIRSTNAME} --lastname ${AIRFLOW_INIT_LASTNAME} --role ${AIRFLOW_INIT_ROLE} --email ${AIRFLOW_INIT_EMAIL}'
  webserver:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: webserver
  scheduler:
    image: *airflow_image
    restart: always
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
      - ./configurations.json:/tmp/conf_file/configurations.json
      - logs:/opt/airflow/logs
    environment: *airflow_environment
    command: scheduler

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_data:/root/.pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  logs:
  pgadmin_data: